apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-app-fe
  namespace: cinema-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-app-fe
  template:
    metadata:
      labels:
        app: cinema-app-fe
    spec:
      containers:
        - name: cinema-app-fe
          image: harbor.local/library/cinema-app-front:5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
